apiVersion: v1
kind: Pod
metadata:
  name: first-pv-pod
spec:
  volumes:
    - name: first-pv-storage
      persistentVolumeClaim:
        claimName: first-pv-claim
  containers:
    - name: first-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "ricardoclesca@~/Utrains/week19/provision-eks-cluster-with-terraform/app-config/mount_data"
          name: first-pv-storage