apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ricardoclesca@~/Utrains/week19/provision-eks-cluster-with-terraform/app-config/mount_data"