apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: dev
  name: utc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: kserge2001/pod-host
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 250Mi
            cpu: 400m
          requests:
            memory: 150Mi
            cpu: 400m
